<a href="https://colab.research.google.com/github/Ar1720/Practise/blob/main/1aa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
s = 2
print (s)
print ('s')

2
s


In [13]:
# cumulative sum


print (s)
s_array = np.array([3, 2, 3, 2])
print(s_array)
t_array = np.array([44, 55, 66])
print(t_array)
s_array = np.concatenate((s_array, t_array))
print (s_array)
# np.cumsum is cumulative sum
u = np.cumsum(s_array)
print (u)



2
[3 2 3 2]
[44 55 66]
[ 3  2  3  2 44 55 66]
[  3   5   8  10  54 109 175]


In [ ]:
time_interval = [4, 6, 12]
t1 = time_interval[0]
t2 = time_interval[1] + t1
t3 = time_interval[2] + t2
print(t1, t2, t3)  # -> 4 10 22